In [1]:
height = [1.87,1.87,1.82,1.91,1.90,1.85]
weight = [81.65,97.52,95.25,92.98,86.18,88.45]
import numpy as np
np_height=np.array(height)
np_weight=np.array(weight)

In [2]:
print(type(np_height))

<class 'numpy.ndarray'>


In [3]:
bmi=np_weight/np_height**2
print(bmi)

[23.34925219 27.88755755 28.75558507 25.48723993 23.87257618 25.84368152]


In [7]:
bmi>23
bmi[bmi>23]

array([23.34925219, 27.88755755, 28.75558507, 25.48723993, 23.87257618,
       25.84368152])

In [8]:
bmi>25
bmi[bmi>23]

array([23.34925219, 27.88755755, 28.75558507, 25.48723993, 23.87257618,
       25.84368152])

In [9]:
bmi>23
bmi[bmi>25]

array([27.88755755, 28.75558507, 25.48723993, 25.84368152])

In [10]:
bmi>25
bmi[bmi>25]

array([27.88755755, 28.75558507, 25.48723993, 25.84368152])

In [11]:
print(bmi>25)

[False  True  True  True False  True]


In [12]:
weight_kg = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

np_weight_kg=np.array(weight_kg)

np_weight_lbs=np_weight_kg*2.2

print(np_weight_lbs)

[179.63  214.544 209.55  204.556 189.596 194.59 ]


In [13]:
dict={"country":["Brazil","Russia","India","China","South Africa","Burma"],"capital":["Brasilia","Moscow","New Delhi","Beijing","Pretoria","Nay Pyi Taw"],"area":[8.516,17.10,3.286,9.597,1.221,0.677],"population":[200.4,143.5,1252,1357,52.98,53.6]}
import pandas as pd
brics=pd.DataFrame(dict)
print(brics)

        country      capital    area  population
0        Brazil     Brasilia   8.516      200.40
1        Russia       Moscow  17.100      143.50
2         India    New Delhi   3.286     1252.00
3         China      Beijing   9.597     1357.00
4  South Africa     Pretoria   1.221       52.98
5         Burma  Nay Pyi Taw   0.677       53.60


In [14]:
brics.index=["BR","RU","IN","CH","SA","BM"]
print(brics)

         country      capital    area  population
BR        Brazil     Brasilia   8.516      200.40
RU        Russia       Moscow  17.100      143.50
IN         India    New Delhi   3.286     1252.00
CH         China      Beijing   9.597     1357.00
SA  South Africa     Pretoria   1.221       52.98
BM         Burma  Nay Pyi Taw   0.677       53.60


In [18]:
cars=pd.read_csv('cars.csv')

In [19]:
print(cars)

      Dimensions.Height  Dimensions.Length  Dimensions.Width  \
0                   140                143               202   
1                   140                143               202   
2                   140                143               202   
3                   140                143               202   
4                   140                143               202   
...                 ...                ...               ...   
5071                 13                253               201   
5072                141                249               108   
5073                160                249               108   
5074                200                210               110   
5075                200                 94               110   

     Engine Information.Driveline  \
0                 All-wheel drive   
1               Front-wheel drive   
2               Front-wheel drive   
3                 All-wheel drive   
4                 All-wheel drive   
...      

In [22]:
cars=pd.read_csv('cars.csv',index_col=0)
print(cars['Identification.Make'])
print(cars[['Identification.Make']])

Dimensions.Height
140           Audi
140           Audi
140           Audi
140           Audi
140           Audi
          ...     
13           Honda
141    Lamborghini
160    Lamborghini
200            BMW
200            BMW
Name: Identification.Make, Length: 5076, dtype: object
                  Identification.Make
Dimensions.Height                    
140                              Audi
140                              Audi
140                              Audi
140                              Audi
140                              Audi
...                               ...
13                              Honda
141                       Lamborghini
160                       Lamborghini
200                               BMW
200                               BMW

[5076 rows x 1 columns]


In [23]:
print(cars['Identification.Make'])
print(cars[['Identification.Make']])
print(cars[['Identification.Make','Identification.Model Year']])

Dimensions.Height
140           Audi
140           Audi
140           Audi
140           Audi
140           Audi
          ...     
13           Honda
141    Lamborghini
160    Lamborghini
200            BMW
200            BMW
Name: Identification.Make, Length: 5076, dtype: object
                  Identification.Make
Dimensions.Height                    
140                              Audi
140                              Audi
140                              Audi
140                              Audi
140                              Audi
...                               ...
13                              Honda
141                       Lamborghini
160                       Lamborghini
200                               BMW
200                               BMW

[5076 rows x 1 columns]
                  Identification.Make         Identification.Model Year
Dimensions.Height                                                      
140                              Audi                  

In [24]:
print(cars[0:4])

                   Dimensions.Length  Dimensions.Width  \
Dimensions.Height                                        
140                              143               202   
140                              143               202   
140                              143               202   
140                              143               202   

                  Engine Information.Driveline  \
Dimensions.Height                                
140                            All-wheel drive   
140                          Front-wheel drive   
140                          Front-wheel drive   
140                            All-wheel drive   

                                 Engine Information.Engine Type  \
Dimensions.Height                                                 
140                        Audi 3.2L 6 cylinder 250hp 236ft-lbs   
140                Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo   
140                Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo   
140            

In [25]:
print(cars[4:6])

                   Dimensions.Length  Dimensions.Width  \
Dimensions.Height                                        
140                              143               202   
91                                17                62   

                  Engine Information.Driveline  \
Dimensions.Height                                
140                            All-wheel drive   
91                             All-wheel drive   

                                 Engine Information.Engine Type  \
Dimensions.Height                                                 
140                Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo   
91                        Audi 3.2L 6 cylinder 265hp 243 ft-lbs   

                   Engine Information.Hybrid  \
Dimensions.Height                              
140                                     True   
91                                      True   

                   Engine Information.Number of Forward Gears  \
Dimensions.Height                      

In [26]:
print(cars.iloc[2])

Dimensions.Length                                                                           143
Dimensions.Width                                                                            202
Engine Information.Driveline                                                  Front-wheel drive
Engine Information.Engine Type                     Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo
Engine Information.Hybrid                                                                  True
Engine Information.Number of Forward Gears                                                    6
Engine Information.Transmission                                                  6 Speed Manual
Fuel Information.City mpg                                                                    21
Fuel Information.Fuel Type                                                             Gasoline
Fuel Information.Highway mpg                                                                 30
Identification.Classification           

In [34]:
print(cars.loc[[140,77]])

                   Dimensions.Length  Dimensions.Width  \
Dimensions.Height                                        
140                              143               202   
140                              143               202   
140                              143               202   
140                              143               202   
140                              143               202   
...                              ...               ...   
77                                60               219   
77                                60               219   
77                                60               219   
77                                60               219   
77                                60               219   

                  Engine Information.Driveline  \
Dimensions.Height                                
140                            All-wheel drive   
140                          Front-wheel drive   
140                          Front-wheel driv